export const PERMISSION = {
  PERMISSIONTYPE: [
    { status: false, value: 'EditClient' },
    { status: false, value: 'DeleteClient' },
    { status: false, value: 'ViewClient' },
    { status: false, value: 'ViewStaff' },
    { status: false, value: 'EditStaff' },
    { status: false, value: 'DeleteStaff' },
    { status: false, value: 'ViewRole' },
    { status: false, value: 'EditRole' },
    { status: false, value: 'DeleteRole' },
    { status: false, value: 'ViewProduct' },
    { status: false, value: 'EditProduct' },
    { status: false, value: 'DeleteProduct' },
    { status: false, value: 'AccessClientSettings' },
    { status: false, value: 'AccessStaffSettings' },
    { status: false, value: 'AccessSetting' },
    { status: false, value: 'EditCompanyProfile' },
    { status: false, value: 'EditLeaveDetail' },
    { status: false, value: 'DeleteLeave' },
    { status: false, value: 'EditHolidayDetail' },
    { status: false, value: 'DeleteHoliday' },
    { status: false, value: 'ViewExpense' },
    { status: false, value: 'EditExpense' },
    { status: false, value: 'DeleteExpense' },
    { status: false, value: 'AccessIntegration' },
    { status: false, value: 'ViewReport' },
    { status: false, value: 'ViewOrders' },
    { status: false, value: 'UpdateOrderDeliveryStatus' },
    { status: false, value: 'UpdateOrderPaymentStatus' },
    { status: false, value: 'UpdateExpenseApprovalStatus' },
    { status: false, value: 'UpdateExpensePaymentStatus' },
    { status: false, value: 'ViewBusinessCard' },
    { status: false, value: 'DeleteBusinessCard' },
    { status: false, value: 'ViewPJP' },
    { status: false, value: 'DeletePJP' },
    { status: false, value: 'EditPJP' },
    { status: false, value: 'PlaceOrder' },
    { status: false, value: 'AddBusinessCard' },
    { status: false, value: 'AddBusinessCards' },
  ],
}
